/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppe3_restauration;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sio2020
 */
public class DemandeP extends javax.swing.JFrame {

    /**
     * Creates new form DemandeParticuliere
     */
    public DemandeP() {
        initComponents();
        lblBackground.setIcon(new ImageIcon("src/main/java/design_img/Page_demande_particuliere.png"));
        
        //Affichage pour un patient non existant
        splitPaneDemandeP.setEnabled(false);
        //Remove
        panelDemandeP.removeAll();
        panelDemandeP.repaint();
        panelDemandeP.revalidate();

        //Affichage
        panelDemandeP.add(panelNonexist);
        panelDemandeP.repaint();
        panelDemandeP.revalidate();

        btnNonexist.getModel().isPressed();

        //Liste déroulante (Type repas)
        DefaultComboBoxModel listeRepas = new DefaultComboBoxModel();
        ArrayList<Repas> lesRepas = Passerelle.tousLesRepas();
        listeRepas.addElement("Choisir un repas");
        for (Repas unRepas : lesRepas) {
            listeRepas.addElement(unRepas);
        }
        comboBoxRepasExist.setModel(listeRepas);
        comboBoxRepasNonexist.setModel(listeRepas);

        //Liste déroulante (Type service)
        DefaultComboBoxModel listeService = new DefaultComboBoxModel();
        ArrayList<Service> lesServices = Passerelle.tousLesServices();
        listeService.addElement("Choisir un service");
        for (Service unService : lesServices) {
            if (unService.getLibelle().compareTo("Restaurateur") == 0 || unService.getLibelle().compareTo("restaurateur") == 0) {
                //On ne l'ajoute pas
            } else {
                listeService.addElement(unService);
            }
        }
        comboBoxServiceNonexist.setModel(listeService);

        //Liste déroulante (Type patient)
        DefaultComboBoxModel listePatient = new DefaultComboBoxModel();
        ArrayList<Patient> lesPatients = Passerelle.tousLesPatients();
        listePatient.addElement("Choisir un patient");
        for (Patient unPatient : lesPatients) {
            listePatient.addElement(unPatient);
        }

        comboBoxPatient.setModel(listePatient);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitre = new javax.swing.JLabel();
        splitPaneDemandeP = new javax.swing.JSplitPane();
        panelChoix = new javax.swing.JPanel();
        lblChoix = new javax.swing.JLabel();
        btnExist = new javax.swing.JButton();
        btnNonexist = new javax.swing.JButton();
        panelDemandeP = new javax.swing.JPanel();
        panelExist = new javax.swing.JPanel();
        lblExist = new javax.swing.JLabel();
        comboBoxPatient = new javax.swing.JComboBox<>();
        lblPatient = new javax.swing.JLabel();
        lblRepasExist = new javax.swing.JLabel();
        comboBoxRepasExist = new javax.swing.JComboBox<>();
        btnValiderExist = new javax.swing.JButton();
        panelNonexist = new javax.swing.JPanel();
        btnValiderNonexist = new javax.swing.JButton();
        lblNonexist = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblIdchambre = new javax.swing.JLabel();
        lblIdservice = new javax.swing.JLabel();
        lblRepasNonexist = new javax.swing.JLabel();
        comboBoxRepasNonexist = new javax.swing.JComboBox<>();
        comboBoxServiceNonexist = new javax.swing.JComboBox<>();
        txtChambre = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitre.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblTitre.setText("DEMANDE PARTICULIERE");
        jPanel1.add(lblTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 240, -1));

        panelChoix.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblChoix.setText("CHOIX ");

        btnExist.setText("Existant");
        btnExist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExistMouseClicked(evt);
            }
        });

        btnNonexist.setText("Non existant");
        btnNonexist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNonexistMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChoixLayout = new javax.swing.GroupLayout(panelChoix);
        panelChoix.setLayout(panelChoixLayout);
        panelChoixLayout.setHorizontalGroup(
            panelChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChoixLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChoix)
                    .addComponent(btnNonexist, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnExist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelChoixLayout.setVerticalGroup(
            panelChoixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChoixLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblChoix)
                .addGap(42, 42, 42)
                .addComponent(btnNonexist)
                .addGap(84, 84, 84)
                .addComponent(btnExist)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        splitPaneDemandeP.setLeftComponent(panelChoix);

        panelDemandeP.setLayout(new javax.swing.OverlayLayout(panelDemandeP));

        lblExist.setText("CHOIX : POUR UN PATIENT EXISTANT");

        comboBoxPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPatient.setText("Patient :");

        lblRepasExist.setText("Repas :");

        comboBoxRepasExist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnValiderExist.setText("VALIDER");
        btnValiderExist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderExistMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelExistLayout = new javax.swing.GroupLayout(panelExist);
        panelExist.setLayout(panelExistLayout);
        panelExistLayout.setHorizontalGroup(
            panelExistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExistLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblRepasExist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxRepasExist, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 157, Short.MAX_VALUE))
            .addGroup(panelExistLayout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(lblExist)
                .addGap(0, 259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValiderExist)
                .addGap(17, 17, 17))
        );
        panelExistLayout.setVerticalGroup(
            panelExistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExistLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblExist)
                .addGap(48, 48, 48)
                .addGroup(panelExistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatient)
                    .addComponent(lblRepasExist)
                    .addComponent(comboBoxRepasExist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(btnValiderExist)
                .addGap(16, 16, 16))
        );

        panelDemandeP.add(panelExist);

        btnValiderNonexist.setText("VALIDER");
        btnValiderNonexist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderNonexistMouseClicked(evt);
            }
        });

        lblNonexist.setText("CHOIX : PATIENT NON EXISTANT");

        lblNom.setText("Nom :");

        lblPrenom.setText("Prénom :");

        lblIdchambre.setText("N° Chambre :");

        lblIdservice.setText("N° Service :");

        lblRepasNonexist.setText("Repas :");

        comboBoxRepasNonexist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxServiceNonexist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelNonexistLayout = new javax.swing.GroupLayout(panelNonexist);
        panelNonexist.setLayout(panelNonexistLayout);
        panelNonexistLayout.setHorizontalGroup(
            panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNonexistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValiderNonexist)
                .addGap(15, 15, 15))
            .addGroup(panelNonexistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNonexist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelNonexistLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRepasNonexist)
                    .addComponent(lblIdservice)
                    .addComponent(lblIdchambre)
                    .addComponent(lblNom))
                .addGap(45, 45, 45)
                .addGroup(panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChambre)
                    .addComponent(comboBoxRepasNonexist, 0, 130, Short.MAX_VALUE)
                    .addComponent(comboBoxServiceNonexist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNom))
                .addGap(58, 58, 58)
                .addComponent(lblPrenom)
                .addGap(18, 18, 18)
                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNonexistLayout.setVerticalGroup(
            panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNonexistLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNonexist)
                .addGap(43, 43, 43)
                .addGroup(panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(lblPrenom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdchambre)
                    .addComponent(txtChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdservice)
                    .addComponent(comboBoxServiceNonexist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelNonexistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepasNonexist)
                    .addComponent(comboBoxRepasNonexist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(btnValiderNonexist)
                .addGap(16, 16, 16))
        );

        panelDemandeP.add(panelNonexist);

        splitPaneDemandeP.setRightComponent(panelDemandeP);

        jPanel1.add(splitPaneDemandeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 120, 890, 450));

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 930, 590));

        jMenu1.setText("Rafraîchir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Retour");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        MenuPersonnel mp = new MenuPersonnel();
        this.dispose();
        mp.setLocationRelativeTo(null);
        mp.setResizable(false);
        mp.show();    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        DemandeP dp = new DemandeP();
        this.dispose();
        dp.setLocationRelativeTo(null);
        dp.setResizable(false);
        dp.show();    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnValiderNonexistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderNonexistMouseClicked
        int noservice = comboBoxServiceNonexist.getSelectedIndex();
        Object service = comboBoxServiceNonexist.getModel().getElementAt(noservice);
        Service unService = (Service) service;

        try {
            //Check si le patient existe. S'il existe demander de d'abord modifier
            Patient unPatient = new Patient(Passerelle.lastId() + 1, Integer.parseInt(txtChambre.getText()), txtNom.getText(), txtPrenom.getText(), noservice);
            ArrayList<Patient> lesPatients = Passerelle.tousLesPatients();

            //Suppose que c'est un nouveau patient
            //A revoir car cela fait bugger l'appli
            boolean estVerifie = true;
            while (estVerifie == true) {
                for (Patient patientExistant : lesPatients) {
                    //Si le nom/prénom/service existe cela retourne faux et le patient n'est pas ajouté
                    if (patientExistant.getNom().toUpperCase().compareTo(unPatient.getNom().toUpperCase()) == 0 && patientExistant.getPrenom().toUpperCase().compareTo(unPatient.getPrenom().toUpperCase()) == 0 && patientExistant.getIdservice() == unPatient.getIdservice()) {
                        estVerifie = false;
                        JOptionPane.showMessageDialog(this, "Le patient existe déjà dans ce service !\nVeuillez contacter le service administratif.");
                    }
                }
            }

            if (estVerifie == true) {
                Passerelle.creerPatient(unPatient);
                int ListeR = comboBoxRepasNonexist.getSelectedIndex();
                Object r = comboBoxRepasNonexist.getModel().getElementAt(ListeR);
                Repas unRepas = (Repas) r;

                Passerelle.commander(unPatient, unRepas);
                JOptionPane.showMessageDialog(this, "Le nouveau patient a été crée et sa commande a été enregistrée !");
            }

            //Refresh
            DemandeP dp = new DemandeP();
            this.dispose();
            dp.setLocationRelativeTo(null);
            dp.setResizable(false);
            dp.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Une erreur est survenue lors de la saisie.\n\nVeuillez vérifier que les informations sont correctement remplies.");
        }
    }//GEN-LAST:event_btnValiderNonexistMouseClicked

    private void btnValiderExistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderExistMouseClicked
        try {
            //Patient
            int ListeP = comboBoxPatient.getSelectedIndex();
            Object p = comboBoxPatient.getModel().getElementAt(ListeP);
            Patient unPatient = (Patient) p;

            //Repas
            int ListeR = comboBoxRepasExist.getSelectedIndex();
            Object r = comboBoxRepasExist.getModel().getElementAt(ListeR);
            Repas unRepas = (Repas) r;

            Passerelle.commander(unPatient, unRepas);
            JOptionPane.showMessageDialog(this, "La commande a été enregistrée !");

            //Refresh
            DemandeP dp = new DemandeP();
            this.dispose();
            dp.setLocationRelativeTo(null);
            dp.setResizable(false);
            dp.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Une erreur est survenue.\n\nVeuillez contacter le service administratif.");
        }
    }//GEN-LAST:event_btnValiderExistMouseClicked

    private void btnExistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExistMouseClicked
        //Remove
        panelDemandeP.removeAll();
        panelDemandeP.repaint();
        panelDemandeP.revalidate();

        //Affichage
        panelDemandeP.add(panelExist);
        panelDemandeP.repaint();
        panelDemandeP.revalidate();
    }//GEN-LAST:event_btnExistMouseClicked

    private void btnNonexistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNonexistMouseClicked
        //Remove
        panelDemandeP.removeAll();
        panelDemandeP.repaint();
        panelDemandeP.revalidate();

        //Affichage
        panelDemandeP.add(panelNonexist);
        panelDemandeP.repaint();
        panelDemandeP.revalidate();
    }//GEN-LAST:event_btnNonexistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemandeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemandeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemandeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemandeP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DemandeP dp = new DemandeP();
                dp.setResizable(false);
                dp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExist;
    private javax.swing.JButton btnNonexist;
    private javax.swing.JButton btnValiderExist;
    private javax.swing.JButton btnValiderNonexist;
    private javax.swing.JComboBox<String> comboBoxPatient;
    private javax.swing.JComboBox<String> comboBoxRepasExist;
    private javax.swing.JComboBox<String> comboBoxRepasNonexist;
    private javax.swing.JComboBox<String> comboBoxServiceNonexist;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblChoix;
    private javax.swing.JLabel lblExist;
    private javax.swing.JLabel lblIdchambre;
    private javax.swing.JLabel lblIdservice;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNonexist;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblRepasExist;
    private javax.swing.JLabel lblRepasNonexist;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPanel panelChoix;
    private javax.swing.JPanel panelDemandeP;
    private javax.swing.JPanel panelExist;
    private javax.swing.JPanel panelNonexist;
    private javax.swing.JSplitPane splitPaneDemandeP;
    private javax.swing.JTextField txtChambre;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables
}
