/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppe3_restauration;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Makara
 */
public class GestionPatient extends javax.swing.JFrame {

    /**
     * Creates new form GestionPatient
     */
    public GestionPatient() {
        initComponents();
        lblBackground.setIcon(new ImageIcon("src/main/java/design_img/Page_modif_supp_patient.png"));

        txtId.setEnabled(false);
        ArrayList<Patient> lesPatients = Passerelle.tousLesPatients();
        for (Patient unPatient : lesPatients) {
            Object tbData[] = {unPatient.getId(), unPatient.getNom(), unPatient.getPrenom(), unPatient.getNumchambre(), unPatient.getIdservice()};
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.addRow(tbData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        lblChambre = new javax.swing.JLabel();
        txtChambre = new javax.swing.JTextField();
        lblService = new javax.swing.JLabel();
        txtService = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(972, 656));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Ajouter");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("Id :");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 40, -1));

        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 160, -1));

        lblNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNom.setText("Nom :");
        jPanel1.add(lblNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 70, 20));

        txtNom.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 160, -1));

        lblPrenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrenom.setText("Prénom :");
        jPanel1.add(lblPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 70, 20));

        txtPrenom.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 160, -1));

        lblChambre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblChambre.setText("Numéro de chambre :");
        jPanel1.add(lblChambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 140, 20));

        txtChambre.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtChambre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 160, -1));

        lblService.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblService.setText("Id du service :");
        jPanel1.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 140, 20));

        txtService.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtService, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 160, -1));

        btnDelete.setText("Supprimer le patient");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prénom", "n° chambre", "id du service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 150, 530, 360));

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        btnModifier.setText("Modifier");
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });
        jPanel1.add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 542, 100, 40));

        jMenu1.setText("Rafraîchir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Retour");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        GestionPatient gp = new GestionPatient();
        this.dispose();
        gp.setResizable(false);
        gp.setLocationRelativeTo(null);
        gp.show();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        MenuPersonnel mp = new MenuPersonnel();
        this.dispose();
        mp.setResizable(false);
        mp.setLocationRelativeTo(null);
        mp.show();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        //Modifie les données
        if (jTable1.getSelectedRowCount() == 1) {
            String str_id = txtId.getText();
            String nom = txtNom.getText();
            String prenom = txtPrenom.getText();
            String str_chambre = txtChambre.getText();
            String str_service = txtService.getText();

            int id = Integer.parseInt(str_id);
            int chambre = Integer.parseInt(str_chambre);
            int service = Integer.parseInt(str_service);

            System.out.println(id + " " + nom + " " + prenom + " " + chambre + " " + service);

            Passerelle.modifierPatient(new Patient(id, chambre, nom.toString(), prenom.toString(), service));

            GestionPatient gp = new GestionPatient();
            this.dispose();
            gp.setResizable(false);
            gp.setLocationRelativeTo(null);
            gp.show();
        }
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        //Suppression du patient bdd
        if (jTable1.getSelectedRowCount() == 1) {
            String str_id = txtId.getText();
            int id = Integer.parseInt(str_id);
            if (Passerelle.supprimerPatient(id) == false) {
                JOptionPane.showMessageDialog(this, "Le patient " + id + " ne peut être supprimé car une commande en son nom a été passé.");
            }

            GestionPatient gp = new GestionPatient();
            this.dispose();
            gp.setResizable(false);
            gp.setLocationRelativeTo(null);
            gp.show();
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();

        String tblId = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String tblNom = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String tblPrenom = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String tblChambre = tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String tblService = tblModel.getValueAt(jTable1.getSelectedRow(), 4).toString();

        txtId.setText(tblId);
        txtNom.setText(tblNom);
        txtPrenom.setText(tblPrenom);
        txtChambre.setText(tblChambre);
        txtService.setText(tblService);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        String str_chambre = txtChambre.getText();
        String str_service = txtService.getText();

        int chambre = Integer.parseInt(str_chambre);
        int service = Integer.parseInt(str_service);

        Passerelle.creerPatient(new Patient(0, chambre, nom.toString(), prenom.toString(), service));

        GestionPatient gp = new GestionPatient();
        this.dispose();
        gp.setResizable(false);
        gp.setLocationRelativeTo(null);
        gp.show();

    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionPatient gp = new GestionPatient();
                gp.setResizable(false);
                gp.setLocationRelativeTo(null);
                gp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModifier;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblChambre;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblService;
    private javax.swing.JTextField txtChambre;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtService;
    // End of variables declaration//GEN-END:variables
}
