/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppe3_restauration;

import javax.swing.ImageIcon;

/**
 *
 * @author sio2020
 */
public class MenuPersonnel extends javax.swing.JFrame {

    /**
     * Creates new form MenuPersonnel
     */
    public MenuPersonnel() {
        initComponents();
        lblBackground.setIcon(new ImageIcon("src/main/java/design_img/Page_soignant.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnDemandeP = new javax.swing.JButton();
        btnSaisie = new javax.swing.JButton();
        btnGestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 600));

        btnExit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnExit.setText("Se déconnecter");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, 150, 40));

        btnDemandeP.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnDemandeP.setText("DEMANDES PARTICULIERES");
        btnDemandeP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDemandePMouseClicked(evt);
            }
        });
        jPanel1.add(btnDemandeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 330, 80));

        btnSaisie.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnSaisie.setText("SAISIE DES REPAS");
        btnSaisie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaisieMouseClicked(evt);
            }
        });
        jPanel1.add(btnSaisie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 330, 70));

        btnGestion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnGestion.setText("GESTION DES PATIENTS");
        btnGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionMouseClicked(evt);
            }
        });
        jPanel1.add(btnGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 330, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDemandePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemandePMouseClicked
        DemandeP aa = new DemandeP();
        this.dispose();
        aa.setLocationRelativeTo(null);
        aa.show();
    }//GEN-LAST:event_btnDemandePMouseClicked

    private void btnSaisieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaisieMouseClicked
        SaisirRepas aa = new SaisirRepas();
        this.dispose();
        aa.setLocationRelativeTo(null);
        aa.show();      }//GEN-LAST:event_btnSaisieMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        Menu aa = new Menu();
        this.dispose();
        aa.setLocationRelativeTo(null);
        aa.show();    }//GEN-LAST:event_btnExitMouseClicked

    private void btnGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionMouseClicked
        // TODO add your handling code here:
        GestionPatient gp = new GestionPatient();
        this.dispose();
        gp.setLocationRelativeTo(null);
        gp.show();
    }//GEN-LAST:event_btnGestionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPersonnel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPersonnel mp = new MenuPersonnel();
                mp.setLocationRelativeTo(null);
                mp.setResizable(false);
                mp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemandeP;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGestion;
    private javax.swing.JButton btnSaisie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
